"""add structured content fields to materials

Revision ID: 2771e62019b3
Revises: 74e950390ed8
Create Date: 2026-07-10 15:28:23.094382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2771e62019b3'
down_revision = '74e950390ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(length=10), nullable=False, server_default='link'))
        batch_op.add_column(sa.Column('content_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('gdrive_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.alter_column('gdrive_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('content_html')
        batch_op.drop_column('content_json')
        batch_op.drop_column('content_type')

    # ### end Alembic commands ###
