"""payments claim flow, invoice date, test rules, teacher meet link, doubt sessions

Revision ID: 74e950390ed8
Revises: b88727e71904
Create Date: 2026-07-07 01:06:18.624505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e950390ed8'
down_revision = 'b88727e71904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doubt_session_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('proposed_dt', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('calendar_event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_event_id'], ['calendar_events.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_records', schema=None) as batch_op:
        batch_op.alter_column('session_date', new_column_name='invoice_date', existing_type=sa.Date(), existing_nullable=False)

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rules', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_meet_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('default_meet_url')

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_column('rules')

    with op.batch_alter_table('payment_records', schema=None) as batch_op:
        batch_op.alter_column('invoice_date', new_column_name='session_date', existing_type=sa.Date(), existing_nullable=False)

    op.drop_table('doubt_session_requests')
    # ### end Alembic commands ###
